config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts






root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
	end
	def new
    @post = Post.new
end

def create
    @post = Post.new post_params
    if @post.save
			redirect_to @post, notice: "Your article was saved"
		else
			render 'new', notice: "Problem! I was unable to save your post."
		end
end  

def edit
end

def update
    if @post.update post_params
			redirect_to @post, notice: "Yeah! Your article has been successfully saved! Feel accomplished!"
		else
			render 'edit'
		end
end 

def destroy
		@post.destroy
		redirect_to posts_path
	end   

def post_params
		params.require(:post).permit(:title, :content, :slug)
	end	

def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


   <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, "Write your article here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post </h1>
    
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Hello Index Page</h1>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.title %>

<%= @post.content %>

<br>
<br>
 
<% link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete Article", post_path(@post), method: :delete, data: { confirm: "Are you sure about deleting this?" } %>